### ISSUE TITLE
Carthage compatability

### ISSUE THREAD

**Issue by ccunnin297** [EurekaCommunity/ViewRow#8]
When attempting to build with Carthage, I get the following error:

```
Dependency "Viewrow" has no shared framework schemes for any of the platforms: iOS
```

**Comment by alldritt** [comment]
I use CocoaPods for my work and I’m not going to be able to install and learn Carthage due to other commitments. If someone wants to work out Carthage support and create a pull request, I’ll happily integrate it.

**Comment by ccunnin297** [comment]
Opened a PR for this: https://github.com/EurekaCommunity/ViewRow/pull/13

**Comment by 368433** [comment]
Helllo I am getting the same : 
Dependency "ViewRow" has no shared framework schemes
message. I was wondering if the latest pull request attempted a fix? Should I change something on my end?

**Comment by ccunnin297** [comment]
If I recall correctly, that was the error I fixed. Try the master branch to see if this fixes your issue.

**Comment by 368433** [comment]
Thanks for clarifying. Yes indeed, this line in the cartfile still leads to the error: 
github "EurekaCommunity/ViewRow"
But it works fine with : github "EurekaCommunity/ViewRow" "master"

**Comment by ccunnin297** [comment]
Yeah, a new release needs to be done in order to have default Carthage functionality work.

**Comment by wousser** [comment]
The error is back again. Both the latest release and master branch are unable to build with Carthage. Same error as above.

**Comment by tihomirbg** [comment]
Same error as above.
Try with:
github "EurekaCommunity/ViewRow"
github "EurekaCommunity/ViewRow" "master
